FROM dockurr/tor

USER root

# Add the edge testing repository and install obfs4proxy
#RUN apk add --no-cache \
#    --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
#    obfs4proxy

USER tor

